# Generated by Django 5.2.16 on 2026-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
